### ISSUE TITLE
[Proposal] Website redesign?

### ISSUE THREAD

**Issue by simonsan** [SFTtech/openage-pr#6]
When talking to people about openage they often ask for a webpage for more info. I have the feeling from questions coming after sending them to our official website, that the website itself and even the repo (which I often send in addition for even more information) for new people doesn't really give all the information in an **easy to find** and **non-overwhelming** way.

So, what do you think of a __rework__ of our the **openage** - website? 

The following examples I took mainly from https://www.projectborealis.com/ and 
https://www.python.org/ .

About the **project borealis** website I like that it is streamlined and all the infos are not overboarding. It's one page layout, that I normally dislike, but here it is really made in a nice and clean way.

The **python website** I personally find too over-boarding with information for a project like openage, where most people want to first be informed about the basic principle of the project itself and afterwards dig deeper into development etc. But I choose it because I find the main menu really clear and also the menu items are really well sorted. You get to the infos you need fast.

Here are some examples what we could add, what we could change and how a good (in my opinion) page could look like from the before mentioned examples:

- add a [media page](https://www.projectborealis.com/#media) with some screenshots of assetpacks (e.g. aoe1de, aoe2de), tools etc.

- give (more) [frequent updates on a small blog-like page](https://www.projectborealis.com/#updates), kind of like the news comment on the reddit, probably more streamlined into a text and not weekly but when something **new** and **exciting** happens

- [documentation/development page](https://www.python.org/doc/) to include blogposts about modding api (subpage dev-blog?), link to future sphinx documentation, etc. basically developer resources, here an example from [openTTD development page](https://www.openttd.org/development.html)

- [core glossary/feature overview](https://github.com/SFTtech/openage/wiki/Core-Glossary), what is working, whats in development, what were planning next. basically an overview what we collected in /docs

- a nice [FAQ](https://www.projectborealis.com/faq) or even more verbose as shown in [Python's FAQ](https://docs.python.org/3/faq/) we could forward people to, when we get asked many of the same questions at once (streams, chat, talks, etc.)  

- [Download page](https://www.python.org/downloads/) collecting latest direct links to downloads (Github releases, Kevin CI builds, bintray), basically the download links should be in a non-outdating form (`latest-xyz.exe`)

- [helpers overview](https://www.projectborealis.com/#join) if and where help would be needed

- [Changelog](https://openrct2.org/changelog)

- in the future something like [server-/community browser](https://servers.openttd.org/en/)

What do you think, would it even make sense to **ask someone professional** to do it for us? I think everyone has already enough to do, also web-design is a good topic to ask someone that is more into the topic then most of us are? Maybe even someone has already an idea who we could ask? 

Please state your ideas, suggestions and/or opinions. Cheers!

__UPDATE:__ Another good example i feel is the website of the game-engine [amethyst](https://amethyst.rs/).

**Comment by simonsan** [comment]
Probably it make sense to stick to static site generation.

Something like [Hugo](https://gohugo.io/) that also [works with markdown](https://gohugo.io/getting-started/quick-start/), is easy to set up and has some good themes ready to use. 

__Examples:__
 - [hugo-icon](https://themes.gohugo.io/theme/hugo-icon/) <= probably my favourite
 - [airspace-hugo](https://themes.gohugo.io/airspace-hugo/)
 - [meghna-hugo](https://themes.gohugo.io/meghna-hugo/)

__Update:__
I asked the guys from **PB** what they use for a static site generator and they were recommending [pelican](https://docs.getpelican.com/en/stable/). Will have a look into both. Pelican seems nice because it supports Markdown and Restructured Text file which will make future C&P from our /docs even simpler if we want to write an News post or something. And it's written in Python, so we don't need to get in touch with another ecosystem for pulling in a dependency as for hugo(?). Sadly they don't have any good templates for us there afaics.

**Comment by TheJJ** [comment]
Sure, the website could should have been overhauled years ago. So whatever solution that is better than the current one, just go for it. I wouldn't hire someone for it, though, we're still a free software project :)

**Comment by simonsan** [comment]
- [ ] Documentation/Development page: WIP
- [ ] FAQ: needs to be updated with some questions also from reddit over the last half a year
- [X] Core glossary: was copied from Wiki
- [ ] Download page: WIP

- [X] Helpers enquiry: Link to github
- [ ] Media page: We should update after the new converter **tbd**
- [ ] News blog: will be possible on the new side, not activated now, as we can do that when we want to have a first entry **tbd**
- [ ] Changelog: Blog like entries? **tbd**

**Comment by TheJJ** [comment]
First improvement happended in #8 :)
